# Exported from Render on 2026-04-02T21:27:06Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: golang-rest-api
      runtime: go
      repo: https://github.com/wallaceinnocent/golang-rest-api
      plan: free
      region: oregon
      buildCommand: CGO_ENABLED=0 go build -tags netgo -ldflags '-s -w' -o app ./cmd/server/main.go
      startCommand: ./app
      autoDeployTrigger: commit
